name: workflow-tst

on:
  push

jobs:
  testing_job1:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        text:
          - miau: 6
            files: 
              - a
              - b
              - c
          - miau: 2
            guau: 1
            files: 
              - d
              - e
              - m
          - miau: 4
            guau: 1
            files: 
              - b
    steps:
      - name: say_hello ${{ matrix.text.miau}}
        run: |
          echo ${{ join(matrix.text.files,'-') }}
