name: workflow-tst

on:
  push

jobs:
  testing_job1:
    runs_on: [ubuntu-latest]
    strategy:
      matrix:
        text: ["hello", "hi", "sayonara"]
    steps:
      - name: say_hello
        run: |
          echo ${{ matrix.text }}
