name: workflow-tst

on:
  push

jobs:
  testing_job1:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        text:
          - miau: 6
            guau: 1
          - miau: 2
            guau: 1
          - miau: 4
            guau: 1
    steps:
      - name: say_hello
        run: |
          echo ${{ matrix.text }}
