name: workflow-tst

on:
  push

jobs:
  testing_job1:
    outputs:
      job_status: ${{ job.status }}
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        text:
          - miau: 6
            files: > 
              a
              b
              c
          - miau: 2
            guau: 1
            files: >
              d
              e
              m
          - miau: 4
            guau: 1
            files: >
              b
    steps:
      - name: normal step
        run: |
          echo miau $RANDOM
      - name: say_hello ${{ matrix.text.miau}}
        run: |
          echo "${{ [{'miau', 'guau'][ matrix.text.guau ] }}"
          echo ${{ matrix.text.files }}
  job2:
    needs: [testing_job1]
    runs-on: [ubuntu-latest]
    steps:
      - name: normal step
        run: |
          echo aaaaaaa
          echo "${{ needs.testing_job1.outputs.job_status }}"
