name: workflow-tst

on:
  push

jobs:
  testing_job1:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        text:
          - hello
            miau: 6
          - adios
            miau: 2
          - sayonara
            miau: 4
    steps:
      - name: say_hello
        run: |
          echo ${{ matrix.text }}
